config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  validates :model, presence: true, uniqueness: true
  validates :color, presence: true
  validates :year, presence: true, numericality: { greater_than: 2000 }
  validates :mileage, presence: true, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car, only: [ :show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.create(car_params)
    if @car.save
      redirect_to car_path(@car), notice: 'New car was successfully added!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to car_path(@car), notice: 'Car was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path, notice: 'Car was successfully destroyed!'
  end

  private

  def find_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:model, :color, :mileage, :year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<div class="mt-3">
  <%= simple_form_for car do |f| %>
    <%= f.input :model %>
    <%= f.input :color %>
    <%= f.input :mileage %>
    <%= f.input :year %>
    <%= f.button :submit, class: 'btn-large btn-success mt-3'%>
  <% end %>
</div>

app/views/cars/edit.html.erb
<h1 class="mt-3">Update  <%= @car.model %> </h1>

<%= render 'form', car: @car %>

app/views/cars/index.html.erb
<h1 class="m-3">All available Cars</h1>

<p class="m-5" id="notice"><%= notice %></p>

<h2> <%= link_to 'Add a new car', new_car_path, class: 'btn-lg btn-info
  text-decoration-none m-3' %> </h2>
<div class="row">
  <% @cars.each do |car| %>
    <div class="col-12 col-md-6 col-lg-4">
      <div class="card m-3">
        <div class="card-body text-center">
          <h3>  <%= link_to car.model , car_path(car), class: 'text-decoration-none'  %> </h3>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<h1 class="mt-3">Add a new car!</h1>

<%= render 'form', car: @car %>

app/views/cars/show.html.erb
<div class="card m-5" style="width: 18rem;">
  <div class="card-body">
    <h3 class="card-title"> <%= @car.model %> </h3>
    <p class="card-text">
      <h5>Color <%= @car.color %> </h5>
      <h5>Mileage <%= @car.mileage %> km</h5>
      <h5>Built in <%= @car.year %> </h5>
    </p>
    <div>
    <%= link_to(edit_car_path, class: "btn btn-success text-decoration-none") do %>
      <spam>Update <%= @car.model %></spam>
    <% end %>
    <%= link_to car_path(@car), method: :delete, data: {
      confirm: "Do you really want to delete this car?" } do %>
      <spam class="btn btn-success text-decoration-none mt-2">Delete <%= @car.model %></spam>
    <% end %>
    </div>
  </div>
</div>
<p class="m-5" id="notice"><%= notice %></p>
<h3 class="m-5"><%= link_to 'Back to all cars', cars_path, class: 'btn-lg btn-success text-decoration-none'  %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>